CREATE TABLE Player (
    StudentID INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Position VARCHAR(50),
    JerseyNumber INT,
    ClassYear VARCHAR(20)
);


INSERT INTO Player (Name, Position, JerseyNumber, ClassYear)
VALUES
  ('Dominic DeLuca', 'LB', 0, 'Redshirt Senior'),
  ('Kyron Hudson', 'WR', 1, 'Redshirt Senior'),
  ('Liam Clifford', 'WR', 2, 'Redshirt Senior'),
  ('Audavion Collins', 'CB', 2, 'Redshirt Junior'),
  ('Antoine Belgrave-Shorter', 'S', 3, 'Redshirt Freshman'),
  ('Koby Howard', 'WR', 3, 'Freshman'),
  ('Tyseer Denmark', 'WR', 4, 'Redshirt Freshman'),
  ('A.J. Harris', 'CB', 4, 'Junior'),
  ('Daryus Dixson', 'CB', 5, 'Freshman'),
  ('Devonte Ross', 'WR', 5, 'Senior'),
  ('Zakee Wheatley', 'S', 6, 'Redshirt Senior'),
  ('Matt Outten', 'WR', 6, 'Freshman'),
  ('Kaden Saunders', 'WR', 7, 'Redshirt Junior'),
  ('Zion Tracy', 'CB', 7, 'Junior'),
  ('Dakaari Nelson', 'LB', 8, 'Redshirt Sophomore'),
  ('Trebor Peña', 'WR', 8, 'Redshirt Senior+'),
  ('Elliot Washington II', 'CB', 9, 'Junior'),
  ('Dejuan Lane', 'S', 10, 'Sophomore'),
  ('Nicholas Singleton', 'RB', 10, 'Senior'),
  ('Lavar Arrington II', 'LB', 11, 'Freshman'),
  ('Lyrick Samuel', 'WR', 11, 'Freshman'),
  ('Anthony Ivey', 'WR', 12, 'Redshirt Junior'),
  ('Xxavier Thomas', 'CB', 12, 'Freshman'),
  ('Kaytron Allen', 'RB', 13, 'Senior'),
  ('Tony Rojas', 'LB', 13, 'Junior'),
  ('Jaxon Smolik', 'QB', 14, 'Redshirt Sophomore'),
  ('Riley Thompson', 'P', 14, 'Senior'),
  ('Braz Thomas', 'S', 14, 'Freshman'),
  ('Drew Allar', 'QB', 15, 'Senior'),
  ('Joshua Johnson', 'CB', 15, 'Freshman'),
  ('Khalil Dinkins', 'TE', 16, 'Redshirt Senior'),
  ('Bekkém Kritza', 'QB', 16, 'Freshman'),
  ('King Mack', 'S', 16, 'Junior'),
  ('Ethan Grunkemeyer', 'QB', 17, 'Redshirt Freshman'),
  ('Kenny Woseley Jr.', 'CB', 17, 'Redshirt Freshman'),
  ('Max Granville', 'DE', 18, 'Redshirt Freshman'),
  ('Josiah Brown', 'WR', 19, 'Redshirt Freshman'),
  ('Jack Lambert', 'QB', 19, 'Redshirt Sophomore'),
  ('Chaz Coleman', 'DE', 19, 'Freshman'),
  ('Mylachi Williams', 'DE', 20, 'Redshirt Freshman'),
  ('Vaboue Toure', 'S', 21, 'Redshirt Freshman'),
  ('Jabree Coleman', 'RB', 21, 'Freshman'),
  ('Tikey Hayes', 'RB', 23, 'Freshman'),
  ('Jahmir Joseph', 'CB', 23, 'Freshman'),
  ('Corey Smith', 'RB', 24, 'Redshirt Freshman'),
  ('Amare Campbell', 'LB', 24, 'Junior'),
  ('Quinton Martin Jr.', 'RB', 25, 'Redshirt Freshman'),
  ('Alex Tatsch', 'LB', 25, 'Freshman'),
  ('Cam Wallace', 'RB', 26, 'Redshirt Sophomore'),
  ('Cam Smith', 'LB', 26, 'Freshman'),
  ('Lamont Payne Jr.', 'S', 27, 'Redshirt Sophomore'),
  ('Zane Durant', 'DT', 28, 'Senior'),
  ('Karson Kiesewetter', 'S', 28, 'Redshirt Sophomore'),
  ('Daniel Jennings', 'DE', 29, 'Freshman'),
  ('Amiel Davis', 'RB', 30, 'Redshirt Senior'),
  ('Kari Jackson', 'LB', 30, 'Redshirt Freshman'),
  ('Logan Cunningham', 'WR', 31, 'Redshirt Junior'),
  ('Kolin Dinkins', 'S', 31, 'Redshirt Junior'),
  ('Keon Wylie', 'LB', 32, 'Redshirt Junior'),
  ('Dani Dennis-Sutton', 'DE', 33, 'Senior'),
  ('Tyler Holzworth', 'RB', 34, 'Redshirt Senior'),
  ('Owen Wafle', 'DT', 34, 'Redshirt Freshman'),
  ('Blaise Sokach-Minnick', 'LS', 35, 'Redshirt Junior'),
  ('Tyler Armstead', 'CB', 35, 'Redshirt Freshman'),
  ('Zuriah Fisher', 'DE', 36, 'Redshirt Senior+'),
  ('Max Heffner', 'DB', 37, 'Freshman'),
  ('Jackson Pryts', 'LB', 38, 'Redshirt Junior'),
  ('Ty Blanding', 'DT', 39, 'Redshirt Sophomore'),
  ('Jashaun Green', 'S', 39, 'Redshirt Junior'),
  ('Anthony Speca', 'LB', 40, 'Redshirt Freshman'),
  ('Mason Robinson', 'DE', 42, 'Redshirt Sophomore'),
  ('Dayshaun Burnett', 'DE', 43, 'Freshman'),
  ('Jaylen Harvey', 'DE', 44, 'Redshirt Freshman'),
  ('Matt Henderson', 'TE', 44, 'Freshman'),
  ('Enai White', 'DT', 45, 'Redshirt Junior'),
  ('Cortez Harris', 'DE', 46, 'Freshman'),
  ('Aidan Probst', 'DE', 47, 'Redshirt Freshman'),
  ('Tyler Duzansky', 'LS', 48, 'Redshirt Senior'),
  ('Cooper Cousins', 'OL', 50, 'Sophomore'),
  ('Alonzo Ford Jr.', 'DT', 50, 'Redshirt Senior+'),
  ('Michael Troutman III', 'OL', 51, 'Freshman'),
  ('Dominic Rulli', 'OL', 52, 'Redshirt Junior'),
  ('Randy Adirika', 'DT', 52, 'Freshman'),
  ('Nick Dawkins', 'OL', 53, 'Redshirt Senior+'),
  ('Xavier Gilliam', 'DT', 54, 'Redshirt Freshman'),
  ('Ian Harvie', 'OL', 54, 'Redshirt Junior'),
  ('TJ Shanahan Jr.', 'OL', 54, 'Redshirt Sophomore'),
  ('Chimdy Onoh', 'OL', 55, 'Redshirt Sophomore'),
  ('Kaleb Artis', 'DT', 58, 'Redshirt Junior'),
  ('Brady O''Hara', 'OL', 59, 'Freshman'),
  ('Liam Horan', 'OL', 61, 'Redshirt Freshman'),
  ('Alex Birchmeier', 'OL', 63, 'Redshirt Sophomore'),
  ('Eagan Boyer', 'OL', 64, 'Redshirt Freshman'),
  ('Jim Fitzgerald', 'OL', 65, 'Redshirt Junior'),
  ('Drew Shelton', 'OL', 66, 'Senior'),
  ('Henry Boehme', 'OL', 67, 'Redshirt Sophomore'),
  ('Anthony Donkoh', 'OL', 68, 'Redshirt Sophomore'),
  ('Garrett Sexton', 'OL', 70, 'Redshirt Freshman'),
  ('Olaivavega Ioane', 'OL', 71, 'Redshirt Junior'),
  ('Nolan Rucci', 'OL', 72, 'Redshirt Senior'),
  ('Caleb Brewer', 'OL', 73, 'Redshirt Freshman'),
  ('J’ven Williams', 'OL', 74, 'Redshirt Sophomore'),
  ('Matt Detisch', 'OL', 75, 'Redshirt Junior'),
  ('Mason Carlan', 'OL', 76, 'Redshirt Senior+'),
  ('Owen Aliciene', 'OL', 77, 'Freshman'),
  ('Malachi Goodman', 'OL', 78, 'Freshman'),
  ('Donnie Harbour', 'OL', 79, 'Redshirt Freshman'),
  ('Jeff Exinor Jr.', 'WR', 80, 'Freshman'),
  ('Donte Nastasi', 'CB', 81, 'Redshirt Sophomore'),
  ('Ethan Black', 'WR', 82, 'Redshirt Sophomore'),
  ('Brian Kortovich', 'TE', 83, 'Freshman'),
  ('Peter Gonzalez', 'WR', 84, 'Redshirt Freshman'),
  ('Luke Reynolds', 'TE', 85, 'Sophomore'),
  ('Aaron Enterline', 'WR', 86, 'Redshirt Freshman'),
  ('Andrew Rappleyea', 'TE', 87, 'Redshirt Sophomore'),
  ('Sam Siafa', 'DT', 88, 'Redshirt Junior'),
  ('Andrew Olesh', 'TE', 88, 'Freshman'),
  ('Finn Furmanek', 'TE', 89, 'Redshirt Sophomore'),
  ('Liam Andrews', 'DT', 90, 'Redshirt Freshman'),
  ('Andrew Dufault', 'LS', 92, 'Redshirt Freshman'),
  ('Bobby Mears', 'DE', 93, 'Redshirt Sophomore'),
  ('Ryan Barker', 'K', 94, 'Redshirt Sophomore'),
  ('De''Andre Cook', 'DT', 94, 'Redshirt Freshman'),
  ('Jordan Mayer', 'DE', 95, 'Redshirt Sophomore'),
  ('Matthew Parker', 'K', 98, 'Freshman'),
  ('Gabriel Nwosu', 'P', 99, 'Redshirt Senior'),
  ('Yvan Kemajou', 'DE', 99, 'Freshman');
